# Makefile

all: clear main receiver packer sender

main:
	gcc -Wall main.c -o main

receiver:
	gcc -Wall receiver.c -o receiver

packer:
	gcc -Wall packer.c -o packer

sender:
	gcc -Wall sender.c -o sender

clear:
	rm -f main