# Makefile

all: main

main: clean
	gcc -Wall main.c -o main
	#gcc -Wall program.c -L. -lbiblioteka -o program
biblioteka: 
#	gcc -c biblioteka.c -o biblioteka.h
#	ar rcs libbilioteka.a biblioteka.o
clean: 
	rm -f main
